useGitIgnore: true

dirs:
  - ./

files:
  - CHANGELOG.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - README.md
  - README.nuget.org.md
  - SECURITY.md
  - PULL_REQUEST_TEMPLATE.md

aliveStatusCodes:
- 200
