name: 'Links validator'


on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - main


jobs:
  link-validation:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v4

    - name: dump
      run: |
        echo 'github.workspace === ${{ github.workspace }}'
        echo "GITHUB_WORKSPACE === $GITHUB_WORKSPACE"

    - name: 'Validate links'
      uses: umbrelladocs/action-linkspector@v1
      with:
        level: 'info'
        fail_on_error: true
        filter_mode: nofilter
        #workdir: ${{ github.workspace }}
        workdir: './'
        config_file: './.github/links-validator.config.yml'
        reporter: 'links-checker'
