name: 'Links validator'


on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - main


jobs:
  link-validation:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v4

    - name: 'Readme analysis'
      uses: umbrelladocs/action-linkspector@v1
      with:
        fail_on_error: true
        config_file: '.github/links-validator.config.yml'
