name: 'Demo .NET'


on:
  workflow_dispatch:

jobs:

  demo-job:
    name: "Demo Job"
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

    - name: "1 - List installed .NET SDKs"
      run: dotnet --list-sdks

    - name: "1 - List installed .NET Runtimes"
      run: dotnet --list-runtimes

    - name: "Setup .NET"
      uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1
      with:
        global-json-file: 'global.json'

    - name: "2 - List installed .NET SDKs"
      run: dotnet --list-sdks

    - name: "2 - List installed .NET Runtimes"
      run: dotnet --list-runtimes
