name: 'Working On - Cache NuGet Packages'


on:
  workflow_dispatch:

  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - main


env:
  SDK_VERSION_8: '8.0.404'
  SDK_VERSION_7: '7.0.410'
  SDK_VERSION_6: '6.0.428'
  SDK_VERSION_5: '5.0.408'
  SDK_VERSION_3: '3.1.426'

  # Set up the .NET environment to improve test performance and reliability
  DOTNET_CLI_TELEMETRY_OPTOUT: true # Disable .NET CLI telemetry
  DOTNET_NOLOGO: true # Disable .NET CLI logo
  DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: true # Enable ANSI color redirection
  TERM: xterm # Enable ANSI color redirection
  NUGET_XMLDOC_MODE: skip # Disable NuGet XML documentation generation


jobs:

  test-job:
    name: "Test job"
    runs-on: ubuntu-22.04

    steps:
    - name: "Debug 0"
      run: echo "Debugging the workflow 02"

    - name: "Checkout"
      uses: actions/checkout@v4.2.2

    - name: "Debug 01"
      run: echo "hashFiles - ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}"

    - name: "Debug 02"
      run: |
        echo "Search all packages.lock.json..."
        find . -type f -name "packages.lock.json" -exec ls -la {} \;

    - name: "Debug 03"
      run: |
        echo "Dump all env variables..."
        echo "----------------------------------------"
        printenv
        echo "----------------------------------------"

    - name: "Cache NuGet packages"
      uses: actions/cache@v4.2.3
      id: cache-nuget
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: ${{ runner.os }}-nuget-

    - name: "Debug 10"
      run: echo "Cache hit - ${{ steps.cache-nuget.outputs.cache-hit }}"

    - name: "Debug 11"
      run: |
        if [ -d ~/.nuget ]; then
          ls -la ~/.nuget
        else
          echo "Dir ~/.nuget not found"
        fi

    - name: "Debug 12"
      run: |
        if [ -d ~/.nuget/packages ]; then
          ls -la ~/.nuget/packages
        else
          echo "Dir ~/.nuget/packages not found"
        fi

    - name: "Setup .NET"
      uses: actions/setup-dotnet@v4.3.1
      with:
        global-json-file: 'global.json'
        dotnet-version: |
          ${{ env.SDK_VERSION_8 }}
          ${{ env.SDK_VERSION_7 }}
          ${{ env.SDK_VERSION_6 }}
          ${{ env.SDK_VERSION_5 }}
          ${{ env.SDK_VERSION_3 }}

    - name: "Restore dependencies"
      run: dotnet restore --locked-mode

    - name: "Build"
      run: dotnet build -c Release --no-restore

    - name: "Pack"
      run: dotnet pack -c Release --no-build

    - name: "Debug 91"
      run: echo "hashFiles - ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}"

    - name: "Debug 92"
      run: |
        echo "Search all packages.lock.json..."
        find . -type f -name "packages.lock.json" -exec ls -la {} \;
