name: 'Working On - Cache NuGet Packages'


on:
  workflow_dispatch:

  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - main


env:
  SDK_VERSION_8: '8.0.404'
  SDK_VERSION_7: '7.0.410'
  SDK_VERSION_6: '6.0.428'
  SDK_VERSION_5: '5.0.408'
  SDK_VERSION_3: '3.1.426'

  # Set up the .NET environment to improve test performance and reliability
  DOTNET_CLI_TELEMETRY_OPTOUT: true # Disable .NET CLI telemetry
  DOTNET_NOLOGO: true # Disable .NET CLI logo
  DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: true # Enable ANSI color redirection
  TERM: xterm # Enable ANSI color redirection
  NUGET_XMLDOC_MODE: skip # Disable NuGet XML documentation generation


jobs:

  test-job:
    name: "Test job"
    runs-on: ubuntu-22.04

    steps:
    - name: "Checkout"
      uses: actions/checkout@v4.2.2

    - name: "Setup .NET"
      uses: actions/setup-dotnet@v4.3.1
      with:
        global-json-file: 'global.json'
        dotnet-version: |
          ${{ env.SDK_VERSION_8 }}
          ${{ env.SDK_VERSION_7 }}
          ${{ env.SDK_VERSION_6 }}
          ${{ env.SDK_VERSION_5 }}
          ${{ env.SDK_VERSION_3 }}

    - name: "Restore dependencies"
      run: dotnet restore

    - name: "Build"
      run: dotnet build -c Release --no-restore

    - name: "Pack"
      run: dotnet pack -c Release --no-build
